on: [push]

jobs:
  profiler-job:
    runs-on: ubuntu-latest
    name: profiler job
    steps:
      - uses: actions/checkout@v3
      - name: Profiler action step
        id: profile
        uses: pdettmann/ammonite-profiler@main
        with:
          entry_file: 'main.py'
          api_key: ${{ secrets.API_KEY }}

 
